README.md
setup.py
ward/suite.py
ward/terminal.py
ward/test_result.py

Output from stderr and stdout will be captured during test execution (and execution of corresponding fixtures), and it will be displayed should a test fail.

Initial implentation of output capturing

---

.github/workflows/build.yml
.github/workflows/pullrequest.yml
tests/test_fixtures.py
tests/test_suite.py
tests/test_testing.py
ward/collect.py
ward/fixtures.py
ward/models.py
ward/suite.py
ward/testing.py

Rewrite of fixture caching to make it more scalable.
This will allow us to support arbitrary fixture scopes much easier (e.g. Hypothesis example can have their own scope).
The rewrite also stops the previous awkward requirement that tests had to run in sequential order. This means we can now support things like randomised test order, and multi-process mode.

Rewrite fixture caching

---

ward/collect.py
ward/run.py

resolves #37 
Updated the click argument for run to accept any number of directories. I noticed while testing that it is possible to supply 0 arguments which may not be desired. Unfortunately, the click library does not have a simple way of accepting a variable number of args and so I had to use a workaround (see run.py).
Updated collect.py to handle a list of directories as well.

added ability to pass multiple dirs to the --path option

---

.github/workflows/release.yml
.gitignore
Makefile

Addresses #38
Here's a few notes:
First, this assumes UNIX-based environment; Makefiles are seldom appropriate for Windows. This should work on any UNIX-like system (Mac/Linux/BSD) with Python 3.6 or later installed. On Ubuntu, you may need to install `python3-venv`, but actually running the Makefile will indirectly prompt the user to install that anyhow. ;)
Second, I'm doing everything in the context of a virtual environment. There's seldom, if ever, a reason not to do this stuff outside of one! The Makefile sets up the venv, installs the necessary packages, and then performs the appropriate tasks.
The virtual environment is never actually activated; its binaries are called directly, and *they* know to only use the venv. It's a neat little trick.
Third, I expanded the `.gitignore`, …

Add Makefile

---

Makefile
requirements.txt
setup.py

Resolved #45 
I've ensured that all tests run with a bootstrapped copy of Ward (*not* the PyPI version) on the following versions:
* Python 3.6.10
* Python 3.7.3
* Python 3.8.1
I have yet to test with PyPy3.6, as I don't presently have that installed, but I can't imagine it would be any different.
I've also added `requirements.txt`. Although it is not needed by `setup.py`, and may feel redundant, it's considered good practice to include, even if just to enable `pip install -r requirements.txt`.
The `setup.py` and `requirements.txt` files should have identical requirements; if they don't, I made a mistake, and you can pitch this back to me.
I've confirmed that this works at a minimum of:
* colorama 0.3.3
* termcolor 1.1.0
* click 7.0
* dataclasses 0.1
It also works with all latest …

Relax Requirements

---

tests/test_suite.py
ward/suite.py

If a module contains parameterised tests that depends on module scoped fixtures, fixture teardown will occur before all tests in the module have been executed. If this module scoped fixture is required again in the same test module, it will be regnerated, but not torn-down again.
This PR attempts to fix that and adds a test to catch this scenario.
The green in the screenshot below shows the order things happen in now when the new test runs with this PR. The red in the screenshot below shows the order of events on 0.23.0b0.

Ensure module-scoped fixtures and parameterised tests interact correctly

---

tests/test_suite.py
ward/run.py
ward/suite.py

Adds `ward --order "random"` which lets you run tests in a random order.
This reduces the likelihood of hidden interdependencies between tests.

Add --order "random" option

---

tests/test_expect.py
tests/test_fixtures.py
tests/test_suite.py
tests/test_testing.py
tests/test_util.py

Converts the remaining test suite for Ward to use plain `assert` statements instead of the `expect` API.

Convert tests to assert

---

tests/test_fixtures.py
tests/test_rewrite.py
tests/test_suite.py
tests/test_terminal.py
tests/test_testing.py
tests/utilities.py
ward/collect.py
ward/testing.py

Fixes a bug around importing something from a module containing tests causing tests to sometimes run more than once. This PR ensures we only run tests for the module they're defined in, and not again in modules they're imported into. Also massively improves test coverage around this area.

Fix test module imports bug

---

ward/rewrite.py

Some of the assertion rewrite methods were missing from the test namespace, meaning tests with certain assertions would raise a `NameError`.

Ensure all assertion rewrite methods are in namespace

---

Makefile
tests/test_expect.py
ward/expect.py
ward/rewrite.py

Fixes #121. Makes it possible to write:
```py
with raises(ValueError) as ctx:
raise ValueError("hi")
assert str(ctx.raised) == "hi"
```
This is similar to [how Pytest does it](https://docs.pytest.org/en/latest/assert.html#assertraises), except that Pytest returns a custom wrapper around the exception ([`ExceptionInfo`](https://docs.pytest.org/en/latest/reference.html#exceptioninfo)), whereas in this PR Ward returns the context manager object itself. I'm honestly not sure which is best. I didn't immediately see a separate wrapper adding much value, and by returning the context manager object you still have access to the `expected_ex_type` later if you need it. But I'm really interested in any opinion about this.
Initially I wanted to return the exception object itself (it just feels more …

Give access to the exception after "with raises"

---

tests/test_suite.py
tests/test_terminal.py
ward/run.py
ward/suite.py
ward/terminal.py
ward/testing.py

This is a solution for #129.
I went with green for the dry-run output. It does not collide with the PASS output because only SKIP and DRYR can occur when ward is run with the `--dry-run` option.

Add --dry-run option to print tests without execution

---

pyproject.toml
requirements.txt
ward/diff.py

Using `pprintpp` to generate reprs which are diffed rather than `pprint`. `pprintpp` generates nicer output and aims for pep8 compliance.

Use pprintpp to generate reprs instead of pprint

---

ward/terminal.py
ward/testing.py

Changes:
```
1. Adding Location footer in AssertionErrors.
```
Concerns:
```
1. Didn't add tests for the change as I can't find other tests for the Locations.
2. Approach doesn't seem clean to me, not sure if how we can improve it.
```
[issue #126 ](https://github.com/darrenburns/ward/issues/126)

Include location footer in logs for AssertionErrors

---

poetry.lock
pyproject.toml
ward/fixtures.py
ward/run.py
ward/terminal.py
ward/tests/test_fixtures.py

(I was up too late and decided to take a crack at #151 ; apologies for not poking that issue in advance. This is my first time looking at Ward, so please let me know if this implementation is just bogus given other design considerations!)
This PR adds a CLI option `--fixtures` that a) prevents tests from executing at all (it does not even print them like in a dry run) and b) prints out information on all defined fixtures. The output from ward's own suite looks like this (I took the liberty of turning an unrelated comment in a fixture into a docstring to show what it would look like):
The simplest way to wire this up was to store off fixture functions to a module-level list in every invocation of the `fixture` decorator. This goes against the "don't look at fixtures until we run tests" …

Add CLI command to show fixture information

---

ward/collect.py

This is a proposed solution to #81 and #157.

ignore site-packages directories when collecting tests

---

ward/diff.py
ward/run.py
ward/terminal.py

To enable Ward to run on CI systems and to aid those with difficulties viewing differences between colours, adds the option to use a more traditional "symbolic" unified diff:
To use symbols instead of colour highlighting call `ward --show-symbols` or add `show_symbols = true` to `pyproject.toml`.

Supporting Ward on CI: Add --show-symbols

---

ward/run.py
ward/suite.py
ward/terminal.py
ward/testing.py
ward/tests/test_suite.py

Fixes #162 issue where tests would not expand, not run, and not fail if parameterisation was incorrect.

Ensure that incorrectly parameterised tests fail as expected

---

ward/rewrite.py
ward/tests/test_rewrite.py

I think I figured out the problem behind #169 : this block of code https://github.com/darrenburns/ward/compare/master...JoshKarpel:lambdas-in-each?expand=1#diff-5bf3f78f564c6863fb8d1277927fc92ddb2a6cfaecbd155c2574bb797dd03138L123
I'm not totally sure what that block of code is supposed to do, but when you pass a `lambda` to an `each`, it ends up in `co_consts`, and the `if` triggers because a `lambda` is a `FunctionType`. The `Test`s function `fn` ends up being replaced with the first `lambda` function from the `each`. The resulting test is not parameterized (because it's `fn` is just some random `lambda`) and passes because it's just invoking the `lambda` function when run.
(This doesn't happen if you just have a default argument which is a `lambda`. I assume this is because when it's an …

Rewrite test functions with `lambda` in `each` correctly

---

.github/dependabot.yml

I don't love how dependabot doesn't group updates, but I find it pretty convenient for bumping GitHub Actions versions since they don't change often and there aren't many of them, and it's outside of people's normal workflow to try to keep them in sync.
(Noticed that you had to do a bump for https://github.com/darrenburns/ward/pull/230)

Add `dependabot.yml` for GHA version bumps

---

docs/source/guide/running_tests.rst
docs/source/guide/writing_tests.rst
poetry.lock
pyproject.toml
setup.cfg
tests/resources/sample_test_dirs/README.md
tests/resources/sample_test_dirs/deeply_nested/my_tests/for_acceptance_test.py
tests/resources/sample_test_dirs/deeply_nested/path/to/more_tests/another_module_of_test.py
tests/resources/sample_test_dirs/deeply_nested/path/to/tests/test_another_example.py
tests/resources/sample_test_dirs/deeply_nested/path/to/tests/test_example.py
tests/resources/sample_test_dirs/deeply_nested/pyproject.toml
tests/test_collect.py
tests/test_config.py
tests/test_util.py
tests/utilities.py
ward/_collect.py
ward/_config.py
ward/_run.py
ward/_terminal.py
ward/_utilities.py
ward/config.py

* Fixes #140 
* Fixes #239
* Fixes issue where `pyproject.toml` defaults were not being applied
* Fixes issue with `dots-module` output where it wouldn't display properly if you were in a directory deeper than a running test module. See the screenshots below.
* Changes `--exclude` to work with paths instead of globs.
* No longer modify `sys.modules` during collection phase.
* Fix `module.__package__` being set incorrectly in some cases.
* Fix issue where `exclude` defined in `pyproject.toml` was not interacting with CLI supplied `--path`s correctly.
* Changes some semantics around running `ward` with no `--path`: it now means "run all tests in my project". If you want to get specific, supply a path. If we can't find the project, then running `ward` is the same as `ward --path .`.
**Now:** …

Several bug fixes

---

docs/source/guide/writing_tests.rst

A simple typo fix (remove an extra backtick)

Fix typo in docs on parameterizing tests

---

docs/source/guide/running_tests.rst
docs/source/guide/writing_tests.rst
ward/_run.py

- Fix `ward fixtures` command. It is broken.
```shell
(venv) $ ward fixtures
Traceback (most recent call last):
File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Python38\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "D:\python\try_ward\venv\Scripts\ward.exe\__main__.py", line 7, in <module>
File "d:\python\try_ward\venv\lib\site-packages\click\core.py", line 1137, in __call__
return self.main(*args, **kwargs)
File "d:\python\try_ward\venv\lib\site-packages\click\core.py", line 1062, in main
rv = self.invoke(ctx)
File "d:\python\try_ward\venv\lib\site-packages\click\core.py", line 1668, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```

Fix broken command 

---

.pre-commit-config.yaml
pyproject.toml
tests/test_diff.py
ward/_collect.py
ward/_debug.py
ward/_diff.py
ward/_suite.py
ward/_utilities.py
ward/fixtures.py

This PR fixes very few type errors, but adds a working configuration. Please see the mypy configuration in pyproject.toml: most of the codebase is still ignored by mypy, but this is a good base to start building on I think.

Introduce mypy (gradually)

---

tests/test_expect.py
ward/expect.py

Currently `raises` only passes if the exact exception type is specified. 
However, sometimes an implementation can choose to raise a private subclass of a public exception class.

Allow subclasses of specified exception class to pass raises assertion

---

pyproject.toml
tests/test_rewrite.py
tests/test_terminal.py
ward/_diff.py
ward/_rewrite.py
ward/_terminal.py
ward/expect.py

Following up on https://github.com/darrenburns/ward/pull/242 , this PR is a take on:
- Introducing pretty output for all comparison failures, in the same titled-panel style we landed on in the other PR.
- Introducing a consistent, extensible way to generate and combine parts of the comparison failure pretty output (it is very easy to add/change parts in the source, and should hopefully be easy to hookify it).
- Revising the existing `==` output to use the titled-panel style.
Incidentally, I extended the output to include assertion messages if present, and allowed for assertion messages that aren't plain strings.
Here's what it looks like right now on this example: [test_examples.txt](https://github.com/darrenburns/ward/files/6603434/test_examples.txt):
I decided to make the two operands …

Add pretty output for all comparison failures

---

pyproject.toml
ward/_terminal.py
ward/testing.py

After this all of the public API is type checked so we may be ready to distribute type data.

Type check `ward.testing`

---

.github/workflows/build.yml
.pre-commit-config.yaml
poetry.lock
pyproject.toml
tests/test_config.py
tests/test_fixtures.py
tests/test_terminal.py
tests/test_testing.py
tests/test_util.py
ward/_config.py
ward/_terminal.py

Fix #323
Additional notes:
- Updated the min Python version to `3.7.13` (latest current version of Python 3.7), since Python 3.6 is EOL.
- Updated the `pre-commit` hooks because the `black` hook was throwing an error.
- Used ignore for all new `mypy` errors because I don't know how they ought to be handled.

Fix 323: Update `rich` dep version

---

.github/workflows/build.yml

Switch to Codecov GitHub action #245 
The simplest way to switch from bash script to **codecov GitHub avtions**.
When reviewing this PR, don't forget the [Codecov Uploader Deprecation Plan](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/?ajs_uid=3169299&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAGAGSaFnp9idItWfHc_FfI_9ATzIEGbDXw_zpIMwSnpY7JNm-93N20JVtZ48KnLyM96xnecM79hwC2zC3iYDtMMFh0l-OuuUo3ON4z5lT6L)

ci: change codecov upload from bash to codecov-action

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml

I was recently introduced to Ward, and I really like the look and feel of it! I like to write my tests with mypy's [strict mode](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict), so I wanted to see if I could help with things like #261.
In the meantime, my freshly cloned copy of this repository would not pass `mypy` checking. Upon investigation, the project depends on `rich@^10.0.0`, but the pre-commit `mypy` hook was pulling down latest due to a lack of a version spec. Since `rich` had breaking changes between `10` and its current of `12`, type checking errors were triggered.
This little PR copies the version specs for non-stub typed dependencies from those specified in `pyproject.toml` over to the `additional_dependencies` section in …

Add versions to mypy hook's additional dependencies

---

tests/test_config.py
tests/test_util.py
tests/utilities.py
ward/_config.py
ward/_run.py

This PR addresses the #330
Changes:
- `set_defaults_from_config` now returns the config instead of string location of the config file
- `test` command picks up plugin config before dropping the rest of config and passes it to config object
- `del` statement instead of `.pop` method to be more explicit about the intent

Plugin config bug fix

---

ward/_rewrite.py

I don't know if or why this makes sense, but it seems to get tests running and passing across Python versions, fixing #352.
Please have a look. Maybe there's a better change to make, but I hope this will be useful in the process of figuring that out.

Only re-indent after rewriting asserts in Py <3.11
